### ISSUE TITLE
T2: Home Page

### ISSUE THREAD

**Issue by Serramento** [Serramento/EcommerceRepository#4]
- Figma Designs: [Figma-Ecommerce-UI-Kit-(Demo-Version)-(Community)](https://www.figma.com/file/tXhNJv706AWM0lXlyxLH9l/E-commerce-UI---Figma-Ecommerce-UI-Kit-(Demo-Version)-(Community))
- Use only `Flex Layout`
- Use only `Tailwind` classes, **no custom classes allowed!**
    - Check [**Customizing Theme and Arbitrary** values on Tailwind](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values)
    - Check [**@apply** directive usage on Tailwind](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply)
    - Check [**Tailwind responsive solution:**](https://tailwindcss.com/docs/responsive-design)
    - Check [**Tailwind switch breakpoints min to max responsive solution:**](https://tailwindcss.com/docs/screens#max-width-breakpoints)

- [x] Create Layout Components like: 
    - [x] Header
**NOTE! There should be only ONE HEADER COMPONENT and ONE MENU for all pages, no color changes needed!**
    - [x] PageContent
(PageContent means a layout container that holds page components and routing definitions)
    - [x] Footer 

- [x] Create Home Page Component Desktop View

- [x] Create Home Page Component Mobile View

- [x] Create repetitive Components like: **ProductCard**

- [x] Slider component
    - [x] Find a slider component can be used in React JS
    - [x] Implement it to Home Page

- [x] Activate **React Router and Links** for Home Page

- [x] Use an **Icon Library** like: FontAwesome (CDN is recommended)

Your folder tree should be like 

```
src/
   components/
       ProductCard.js
   layout/
       Header.js
       PageContent.js
       Footer.js
   pages/
       HomePage.js
       ...
```

**Comment by Serramento** [comment]
@gokhanozdemir hocam ben dosyaları .jsx olarak ayarladım ama yanlış mı? Hata veriyordu böyle düzeltebildim. Tailwind'de söylediğiniz confige ekledim ama sürekli takılıyor, sayfada değişiklik yapıp kaydetsem de göremiyorum localhost'ta. Dosyayı kapatıp tekrar açmam gerekiyor. Yardımcı olabilirseniz sevinirim.

**Comment by gokhanozdemir** [comment]
Kesinlikle yanlış değil. vite, react projeleri için özellikle jsx işleyecek şekilde ön tanımlı

**Comment by Serramento** [comment]
@gokhanozdemir hocam merhaba. Sayfa yerleşimini yapmaya çalışıyorum desktop için, ancak sol ve sağ tarafında beyaz boşluk kalıyor bir türlü genişletemiyorum sayfayı. w-screen yapınca yapısı bozuluyor. w-[...rem] yapınca sayfa sağa kayıyor sol ve üstte geniş boşluk kalıyor. Nasıl yapmam gerek yardımcı olursanız sevinirim.

**Comment by erhanfirat** [comment]
bazı görseller arkaplan olarak çalışmıyor.

**Comment by erhanfirat** [comment]
Desktop view kenar boşlukları düzeltilmeli

**Comment by Serramento** [comment]
@gokhanozdemir hocam tamamlamıştım bunu pull request yapayım mı?

**Comment by gokhanozdemir** [comment]
Desktop'da header sağ solundaki boşluklar dışında genel hizalamalar düzgün güzel olmuş Issue'yu kapatabilirsiniz.
